command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: DATABRICKS_HOST
    value: "dbc-bdb63e4d-dfd2.cloud.databricks.com"

  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/7e376065f3d183c9"

  - name: WAREHOUSE_ID
    value: "7e376065f3d183c9"

  - name: CATALOG
    value: "workspace"

  - name: SCHEMA
    value: "default"

  - name: TABLE
    value: "prescriber_search_poc"

  - name: LOCAL_TEST_EMAIL
    value: "henry.whitfield@ucb.com"